### PR TITLE
Adding event handlers

### PR DESCRIPTION
**Pull request by jbw3**
Here's a start on event handlers. I decided to try the approach of adding functions like `on_attack()` and `on_play()` to the base `Card` class. These functions do nothing by default, but can be overridden by derived classes. I used them to implement Moat and Merchant's functionalities.

I put some though into creating an event registry class and having cards register events, but I was afraid that would become more complicated. Cards would have to register events when they were drawn, and unregister them when they were discarded (otherwise the events could be triggered when they were in the deck or discard pile).

Let me know what you think.

### CODE REVIEW

**Comment by evanofslack** [comment]
Thanks for checking this out. 

I need to take some time to think more about this. I honestly am not sure the best way forward. I think your approach is solid. Especially for base and intrigue where the effects aren't too complicated. 

 I'll try to revisit this and leave some more flushed out thoughts later.

**Comment by jbw3** [comment]
Sounds good. I thought about this a little more today. I think most cards can be handled if we add a few more functions like `on_trash()`, `on_gain()`, `on_discard()`, etc. I think we should be able to handle [Reaction](http://wiki.dominionstrategy.com/index.php/Reaction) cards this way. This would also work for cards like [Lighthouse](http://wiki.dominionstrategy.com/index.php/Lighthouse) and [Guardian](http://wiki.dominionstrategy.com/index.php/Guardian) that prevent attacks.

I did realize that one problem it would not solve is non-card things like [Landmarks](http://wiki.dominionstrategy.com/index.php/Landmark), [Projects](http://wiki.dominionstrategy.com/index.php/Project), and [Allies](http://wiki.dominionstrategy.com/index.php/Ally).

**Comment by jbw3** [comment]
I decided to play around with adding an `EventHandler` class and pushed up an idea. This should better handle [Landmarks](http://wiki.dominionstrategy.com/index.php/Landmark), [Projects](http://wiki.dominionstrategy.com/index.php/Project), [Allies](http://wiki.dominionstrategy.com/index.php/Ally), etc. as they can register events to be called. `EventHandler` can, of course, be expanded to handle more events like trashing, discarding, etc.

Note that I have `Player` register events instead of cards. This is because (as mentioned in a previous comment) we don't want to trigger all cards event handlers as they may be in the deck or discard pile. Thus, I had to have `Player` trigger events on the appropriate cards.

Also, I'm not sure how to handle attacks. They are a bit different as they are not fire-and-forget events, but rather need to pass a boolean back to indicate whether each player is attacked. This gets a little more challenging with an event handler.

I'm not sure this is the best approach but wanted to push it up to see if you had any thoughts.

**Comment by evanofslack** [comment]
This is more along the lines of how I originally envisioned it. I think the syntax is a better more confusing but it also allows us to cover a wider range of cases later on.

**Comment by jbw3** [comment]
Sounds good! I'll think about the attack case a bit more and see if I can come up with a solution.

**Comment by jbw3** [comment]
After a ~~brief~~ long break I've picked this issue back up again. I still have a bit of work to do, but I wanted to get your thoughts on what I've done so far. Dominion has a lot of complex edge cases with different cards, but the code is much more flexible now and should be able to handle a variety of cases.

First of all, I decided to rename what I was calling "events" to "effects". This is because Dominion has landscape cards called "events", and I wanted to avoid confusion. I took the name "effects" from the [Dominion wiki](https://wiki.dominionstrategy.com/index.php/Triggered_effects).

I added a `set_up()` method to the `Card` class that can be overridden by derived classes. I needed this to allow cards to register effects at the beginning of the game, but it is also useful for other cases as several cards (e.g. [Baker](https://wiki.dominionstrategy.com/index.php/Baker), [Young Witch](https://wiki.dominionstrategy.com/index.php/Young_Witch), etc.) do something at the start of the game.

The last main challenge I'm working right now is providing a way for players to pick the order in which effects resolve when there are multiple. For example, if one effect draws cards and another effect trashes cards, the player will want to pick the order in which they occur. However, I don't want to prompt players for every effect because if effect are doing simple things like +cards or +money, the order in which they occur doesn't matter. I added the `EffectOrderType` enum as my first attempt at categorizing the order in which effects should execute. However, when thinking through explaining how it worked for this writeup, I realized it is a bit awkward and doesn't cover all cases well. I'm currently thinking though how to redesign it.

Let me know your thoughts on my design and implementation.

**Comment by TheBluekr** [comment]
In my personal games I tend to do the order of effects from a card from top to bottom, in order, and continue stepwise when the previous effect is done. This should get rid of the difficulty of figuring out the order of effect from any cards.
The difficulty really starts as soon as [First Mate](https://wiki.dominionstrategy.com/index.php/First_Mate) from Plunder gets involved. Especially if it's combined with itself as the effect is ongoing until it finishes recursively.

**Comment by jbw3** [comment]
@TheBluekr
Yes, in general, the things a card does are evaluated from top to bottom. However, the effects I've been working on in this issue are things triggered from Reactions, when-trashed/when-gained cards, etc. In these cases, the player gets to choose the order: [Triggered Effects](https://wiki.dominionstrategy.com/index.php/Triggered_effects).

**Comment by TheBluekr** [comment]
> @TheBluekr Yes, in general, the things a card does are evaluated from top to bottom. However, the effects I've been working on in this issue are things triggered from Reactions, when-trashed/when-gained cards, etc. In these cases, the player gets to choose the order: [Triggered Effects](https://wiki.dominionstrategy.com/index.php/Triggered_effects).

I've decided to look a bit deeper into it.
https://wiki.dominionstrategy.com/index.php/Reaction
Order actually as specified here isn't fully decided. What's interesting for example is with [Black Cat](https://wiki.dominionstrategy.com/index.php/Black_Cat), any other drawn due to the +2 Cards will trigger too until it's fully resolved.
Would it make some more sense for the player to decide themselves which order of effects they decide to trigger by providing a list of positions and recursively resolve every card?

**Comment by jbw3** [comment]
Yes, the player should be the one to decide the order when the order of effects matters, and I already have that part implemented. The part I'm trying to figure out now is how to determine when to ask the player. For example, if a player plays [Caravan](https://wiki.dominionstrategy.com/index.php/Caravan) and [Sea Witch](https://wiki.dominionstrategy.com/index.php/Sea_Witch), there will be two effects registered for the start of the next turn: "+1 card" and "+2 cards, discard 2 cards". The order in which these effects occur matters, so the player should get to decide the order. However, if a player plays [Caravan](https://wiki.dominionstrategy.com/index.php/Caravan) and [Wharf](https://wiki.dominionstrategy.com/index.php/Wharf), the next-turn effects will be "+1 card" and "+2 cards, +1 buy". The order in which these effects occur do not matter, so I don't want to ask the player unnecessarily. Figuring out when order matters for a combination of effects and when it does not is the challenge. However, I think I've got an idea. I just have not had time to code and test it yet.

With regard to having `on_attack()`, etc. methods on cards: we discussed that in the conversation above but decided to go with the effect registry because it handles a wider variety of cases.

**Comment by evanofslack** [comment]
Great changes coming in so far, seems well thought out. 

If its too difficult to determine when effect order does not matter vs does matter, I think its fine to always prompt player for order. Should be a fine compromise for now. If you can come up with a mechanism to determine order importance, that'd be cool to see too. Let me know if you have idea for that.

**Comment by jbw3** [comment]
@evanofslack I've got an implementation that only prompts the player when necessary. I realized the main reason for prompting the player is when multiple effects want to both add and remove cards from the player's hand (e.g. one effect draws cards and another effect discards cards). I added the `EffectAction` enum to effects for them to specify whether they add to or remove from a player's hand or if they do neither (e.g. they add money or buys). I then implemented logic in the `_need_player_order()` method to see if the player needs to be prompted to order the effects. I believe this should cover most cases, and if there is another case we come across, it should not be too hard to add another enum value and some code to handle that case.

I also now have logic to handle the [Black Cat](https://wiki.dominionstrategy.com/index.php/Black_Cat) case that @TheBluekr brought up. Essentially, now new effects can be registered in the handling of another effect.

I have now implemented everything that I was planning to. Let me know your thoughts or if you think I missed anything.

**Comment by evanofslack** [comment]
@jbw3  Thanks for getting this all working, really great changes. Looks like a great fundamental building block that will ensure new cards can be added. 

I'll merge this request. Are there any bugs fixed or has all implementation been kept the same? If retained, ill hold off on doing a new release.

**Comment by jbw3** [comment]
You're welcome!

I don't think there were any bugfixes, so all implementation should be the same.

**Pull request merged**
